/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.EncriptarPasswords;
import controlador.UsuarioController;
import javax.swing.JOptionPane;
import modelo.ConexionBD;
import modelo.Usuario;

/**
 *
 * @author esanarru
 */
public class LoginForm extends javax.swing.JFrame {

    private ConexionBD conexionBD;
    private EncriptarPasswords decodificador;
    private UsuarioController controlador;

    public LoginForm() {
        initComponents();
        conexionBD = new ConexionBD("root", "admin");
        decodificador = new EncriptarPasswords();
        controlador = new UsuarioController();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLBienvenido = new javax.swing.JLabel();
        JLInicioSesion = new javax.swing.JLabel();
        JLContraseña = new javax.swing.JLabel();
        JLUsuario1 = new javax.swing.JLabel();
        JTFUsuario = new javax.swing.JTextField();
        JTFPassword = new javax.swing.JTextField();
        JBInicioSesión = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JLBienvenido.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        JLBienvenido.setText("¡Bienvenido al Sistema!");

        JLInicioSesion.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        JLInicioSesion.setText("Iniciar Sesión");
        JLInicioSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLInicioSesionMouseClicked(evt);
            }
        });

        JLContraseña.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        JLContraseña.setText("Contraseña:");

        JLUsuario1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        JLUsuario1.setText("Usuario:");

        JTFUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFUsuarioActionPerformed(evt);
            }
        });

        JTFPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFPasswordActionPerformed(evt);
            }
        });

        JBInicioSesión.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        JBInicioSesión.setText("Iniciar Sesión");
        JBInicioSesión.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBInicioSesiónMouseClicked(evt);
            }
        });
        JBInicioSesión.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBInicioSesiónActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel1.setText("Regístrese");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JLUsuario1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JTFPassword, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JTFUsuario, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                                .addComponent(JLBienvenido)))
                        .addGap(98, 98, 98))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JLContraseña)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(JLInicioSesion)
                        .addGap(152, 152, 152))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(JBInicioSesión))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(JLBienvenido)
                .addGap(18, 18, 18)
                .addComponent(JLInicioSesion)
                .addGap(18, 18, 18)
                .addComponent(JLUsuario1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JTFUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JLContraseña)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JTFPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JBInicioSesión)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTFUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFUsuarioActionPerformed

    private void JTFPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFPasswordActionPerformed

    private void JBInicioSesiónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBInicioSesiónActionPerformed
        Usuario miUsuario = new Usuario();
        String Password = "";
        if (!JTFUsuario.getText().trim().equals("") && !JTFPassword.getText().trim().equals("")) {
            if (conexionBD.setConexion()) {
                miUsuario = controlador.getUsuario(JTFUsuario.getText().trim());
                Password = decodificador.codificar(JTFPassword.getText().trim());
                if (Password.equals(miUsuario.getPassword())) {
                    JOptionPane.showMessageDialog(null, "Bienvenido al Sistema");
                    this.dispose();
                    MenuPrincipal menu = new MenuPrincipal();
                    menu.show();
                } else {
                    JOptionPane.showMessageDialog(null, "Contraseña incorrecta");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Error al conectar");

            }
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese el usuario y la contraseña");
        }
    }//GEN-LAST:event_JBInicioSesiónActionPerformed

    private void JLInicioSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLInicioSesionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JLInicioSesionMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.dispose();
        RegistroForm registro = new RegistroForm();
        registro.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void JBInicioSesiónMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBInicioSesiónMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JBInicioSesiónMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBInicioSesión;
    private javax.swing.JLabel JLBienvenido;
    private javax.swing.JLabel JLContraseña;
    private javax.swing.JLabel JLInicioSesion;
    private javax.swing.JLabel JLUsuario1;
    private javax.swing.JTextField JTFPassword;
    private javax.swing.JTextField JTFUsuario;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
