/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.InventarioController;

import javax.swing.JOptionPane;
import controlador.InventarioListener;
import modelo.InventarioModel;
import controlador.InventarioController;
import modelo.ConexionBD;
import modelo.InventarioModel;

/**
 *
 * @author esanarru
 */
public class MenuPrincipal extends javax.swing.JFrame implements Vista {
    // ... el resto del código ...

    private InventarioController inventarioController;

    public MenuPrincipal(ConexionBD conexionBD) {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);

        // Create instances of models and controllers
        InventarioModel inventarioModel = new InventarioModel(conexionBD);
        InventarioVista inventarioVista = new InventarioVista();
        InventarioController inventarioController = new InventarioController(inventarioModel);

        inventarioVista.setInventarioController(inventarioController);
        inventarioController.setInventarioVista(inventarioVista);  // Add this line

        this.inventarioController = inventarioController;  // Make sure to assign the controller to the class field
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLSistemaGestion = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        JBChat = new javax.swing.JButton();
        JBInventarios = new javax.swing.JButton();
        JBVentas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JLSistemaGestion.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        JLSistemaGestion.setText("¡Sistema de Gestión!");

        jButton1.setText("Usuarios");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        JBChat.setText("Chat");
        JBChat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBChatMouseClicked(evt);
            }
        });

        JBInventarios.setText("Inventarios");
        JBInventarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBInventariosMouseClicked(evt);
            }
        });

        JBVentas.setText("Ventas");
        JBVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBVentasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JBInventarios, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(JBVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JBChat, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JLSistemaGestion)
                .addGap(106, 106, 106))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(JLSistemaGestion)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBInventarios, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBChat, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        this.dispose();
        RegistroClienteForm registroCliente = new RegistroClienteForm();
        registroCliente.show();
    }//GEN-LAST:event_jButton1MouseClicked

    private void JBInventariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBInventariosMouseClicked
        if (inventarioController != null) {
            inventarioController.mostrarSeccionInventario();
        } else {
            System.out.println("InventarioController is null");
        }

    }//GEN-LAST:event_JBInventariosMouseClicked

    private void JBChatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBChatMouseClicked
        this.dispose();
        ServidorForm servidor = new ServidorForm();
        ClienteForm cliente = new ClienteForm();
        servidor.show();
        cliente.show();
    }//GEN-LAST:event_JBChatMouseClicked

    private void JBVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBVentasMouseClicked
        this.dispose();
        VentasForm venta = new VentasForm();
        venta.show();
    }//GEN-LAST:event_JBVentasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        ConexionBD conexionBD = new ConexionBD("root", "Arceus10");
        InventarioModel inventarioModel = new InventarioModel(conexionBD);
        InventarioController inventarioController = new InventarioController(inventarioModel);
        InventarioVista inventarioVista = new InventarioVista();

        inventarioVista.setInventarioController(inventarioController);
        inventarioController.setInventarioVista(inventarioVista);
        inventarioController.agregarListener(inventarioVista);
        inventarioVista.mostrar();  // Add this line
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBChat;
    private javax.swing.JButton JBInventarios;
    private javax.swing.JButton JBVentas;
    private javax.swing.JLabel JLSistemaGestion;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actualizarInventario() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void mostrarSeccionInventario() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void setInventarioController(InventarioController inventarioController) {
        this.inventarioController = inventarioController;
    }

}
